Rebuilt net stack. Dev commit - blocked by type errors.
* `type annotations required: cannot resolve '<_ as futures::Sink>::SinkItem == sirpent::Msg'` (src/main.rs:93)
  I haven't a good model of what/why this isn't resolved. Attempts at type annotations so
  far have had no effect.
* `expected struct 'futures::FutureResult', found struct 'futures::MapErr'` (src/main.rs:162)
  This is made harder to debug by use of impl Trait. Put a grounded type on play_game and
  see if it starts to make sense.
* `if and else have incompatible types` (src/main.rs:222)
  This one can be resolved. The messaging decision should be wrapped up somehow. Cleaner.